services:

  db:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_DB: guacamole
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: guacamole
    volumes:
    - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
    - data:/var/lib/postgresql/data

  guacd:
    image: guacamole/guacd:1.5.5
    volumes:
    - drive:/drive
    - record:/record

  guacamole:
    image: guacamole/guacamole:1.5.5
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_HOSTNAME: db
      POSTGRESQL_DATABASE: guacamole
      POSTGRESQL_USER: guacamole
      POSTGRESQL_PASSWORD: secret
    depends_on:
    - guacd
    - db

  proxy:
    image: nginx:1.27.5-alpine
    ports:
    - 8080:8080
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
    - guacamole

volumes:
  data:
  drive:
  record:
